---
abstract: 'Wrap URLs from @ARGV for fetching and content consumption with <>'
author:
  - 'Olivier Mengué <dolmen@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200014, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ARGV-URL
requires:
  LWP: 5
resources:
  homepage: https://github.com/dolmen/p5-ARGV-URL
  repository: https://github.com/dolmen/p5-ARGV-URL
version: 0.91
